
replicaCount: 1
image:
  repository: welcomeappacr.azurecr.io/welcomeapp
  tag: v1
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""

service:
  name: welcomeappdemo
  type: LoadBalancer
  port : 80
  internalPort : 8080

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  tls: []
resources: {}
nodeSelector: {}

tolerations: []

affinity: {}
